#!/usr/bin/env python3
import click
from omxplayer.player import OMXPlayer
from pathlib import Path
from time import sleep


@click.command()
@click.argument('shows', nargs=-1)
@click.option('--amount', '-n', help='amount of episodes to play')
@click.option('--random/--not-random', '-R', help='play random episodes')
@click.option('--episode', '-e', help='play specific episode')
def main():
    """Wrapper for OMXPlayer intended for playing TV shows on my Raspberry Pi.
    """
    print("Hello.")


player = OMXPlayer(
    "/volume1/shows/Bob's.Burgers.S01.1080p.AMZN.WEB-DL.DD+5.1.x264-Cinefeel/Bob's.Burgers.S01E01.Human.Flesh.1080p.AMZN.WEB-DL.DD+5.1.x264-Cinefeel.mkv",
)
sleep(5)
player.quit()
