#!/bin/bash

if [ -z "$1" ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]
then
    cat <<EOF
usage: tv COUNT SHOW [SHOW]...
EOF
    exit 0
fi

if ! [[ $1 =~ ^[1-9]+$ ]]
then
    echo "Please supply a valid positive integer."
    exit 1
fi

playcount=$1
shift

cd /media/data/libraries/shows
find -L "$@" -type f | shuf -n $playcount | videoplay
