#!/bin/bash

if [ -n "$1" ];
then
	interval=$1
else
	interval=5
fi

while true
do
	sleep $interval  # Execute body every `$interval` seconds.
	tagcache_changed=$(find /var/lib/mpd/tag_cache -ctime $interval)
	if [ -z "$tagcache_changed" ];
	then
		systemctl restart mpd
	fi
done
