#!/bin/bash

inotifywait -e close_write,moved_to,create -m /media/data/libraries/music |
while read -r directory events filename
do
	if [ "$filename" = "tag_cache" ]
	then
		systemctl restart mpd
	fi
done
