#!/bin/bash

# If not connected to terminal, then assumed piped stdin.
if ! [ -t 0 ]
then
    filenamesfromstdin=$(cat < /dev/stdin)  # Expected to be \n delimited.
fi

originalIFS=$IFS
IFS=$'\n'
for file in $filenamesfromstdin $@;  # First process stdin, then commandline arguments.
do
    tty=/dev/$(ps hotty $PPID)  # Get TTY of parent process.
    filepath=$(realpath $file)
    echo -en "\033[1mPlaying\033[m: $filepath\n"
    omxplayer -r -o hdmi "$file" < $tty  # Use parent TTY as stdin to maintain keyboard control.
    echo -en "\n\n"
done
IFS=$originalIFS
